server:
  port: 9000
  
spring:
  cloud:
    gateway:
      routes:
        #Route Mapping
      - id: loginMicroservice               #RouteIdentifier
        uri: http://localhost:9002/         #Respective microservice URL which needs to be mapped
         #Request Context Path Mapping
        predicates:
        - Path=/ecommerce/login/**          
        
        #Route Mapping - With out Filters - Version 2 Request
      - id: orderMicroservice
        uri: http://localhost:9001/
        predicates:
        - Path=/ecommerceV2/**

        #Route Mapping - With Filters - Version 1 Request
      - id: orderMicroservice
        uri: http://localhost:9001/
        predicates:
        - Path=/ecommerce/** 
        filters:
        - RewritePath=/ecommerce, /ecommerceV2/      #Rewriting the path 
        
        # PreFilter - AddRequestHeader=custom-Request-header, customer-Request-header-value
        # PostFilter - AddResponseHeader=custom-Request-header, customer-Response-header-value
        