server:
  port: 9000
  
spring:
  cloud:
    gateway:
      routes:
      #Route Mapping
      - id: loginMicroservice               #RouteIdentifier
        uri: http://localhost:9002/         #Respective microservice URL which needs to be mapped
        predicates:
        - Path=/ecommerce/login/**          #Request Context Path Mapping
        
        #Route Mapping
      - id: orderMicroservice
        uri: http://localhost:9001/
        predicates:
        - Path=/ecommerce/order/**